### ISSUE TITLE
[GLITCH] Overlap of Course Title

### ISSUE THREAD

**Issue by Sujas-Aggarwal** [devclub-iitd/ClassGrid#4]
After authenticating, in the timetable, the course titles overlap to look glitchy like this.
![image](https://github.com/user-attachments/assets/41cddecc-4abf-4564-9e82-ba5239ed7417)
![image](https://github.com/user-attachments/assets/2ca039ad-3afc-445d-a3ba-59c54bcd5a91)
Somehow there is another block below that block, CVL341 has CVL341A Block below it with some transparency.
![image](https://github.com/user-attachments/assets/d4343dd2-680d-41e1-8ced-bba4f8aa764c)
I think the reason behind this is, that the course I am enrolled in has been divided into 2 sections A and B and since I am allotted A, I am getting a course CVL341A at the same time as CVL341 since they are the same course. 
But Because the blocks are translucent, they look glitchy.
One possible solution might be to make the blocks opaque, discard one of the 2 overlapping or add a third dimension to the table.
It will also help you to auto-discard the 341 since 341A is more precise.

**Comment by shashmahawar** [comment]
This is an issue where an incorrect course has been mapped to you. Please raise an issue filling this form : https://forms.gle/soGbPnr8toBRQAUz7.
